[workspace]
members = ["packages/*"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
vexide = "0.7.0"
atum = { path = "packages/atum" }
log = "0.4.27"