[package]
name = "atum"
version = "0.1.0"
edition = "2021"

[dependencies]
vexide = { workspace = true }
log = { workspace = true }

bytemuck = { version = "1.23.2", features = ["derive"] }
nalgebra = { version = "0.34.0", default-features = false, features = ["alloc", "libm", "macros"] }
vex-sdk = "0.26.0"