[package]
name = "atum"
version = "0.1.0"
edition = "2021"

[dependencies]
vexide = { workspace = true }
slint = { workspace = true }
vexide-slint = { workspace = true }
log = { workspace = true }

bytemuck = "1.23.1"
nalgebra = { version = "0.33.0", default-features = false, features = ["alloc", "libm", "macros"] }
vex-sdk = "0.26.0"

[build-dependencies]
slint-build = "1.9.1"
