[package]
name = "stout-drive"
description = "left: bottom(6-8) top(9-10), right: bottom(16-18) top(19-20)"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# These fields configure default behavior for uploads with `cargo v5`.
[package.metadata.v5]
upload-strategy = "differential"
slot = 1
icon = "robot"
compress = true

[dependencies]
atum = { workspace = true }
vexide = { workspace = true }
uom = { workspace = true }
log = { workspace = true }
